CDEBUG = -g

PROG = charts_image_module

CPP_SRC = \
image_module.cpp \

EXTRA_CFLAGS = \
-I$(INC_DIR)/CQCharts \
\
-I/usr/include/x86_64-linux-gnu/qt5/QtGui \
-I/usr/include/x86_64-linux-gnu/qt5/QtCore \
-I/usr/include/x86_64-linux-gnu/qt5 \

include $(MAKE_DIR)/shlib.mk
