CDEBUG = -g

PROG = charts_mandelbrot_module

CPP_SRC = \
CMandelbrot.cpp \
CColorRange.cpp \
mandelbrot.cpp \

EXTRA_CFLAGS = \
-I$(INC_DIR)/CQCharts \
\
-I/usr/include/x86_64-linux-gnu/qt5/QtGui \
-I/usr/include/x86_64-linux-gnu/qt5/QtCore \
-I/usr/include/x86_64-linux-gnu/qt5 \

include $(MAKE_DIR)/shlib.mk
