load -csv sea_level.csv -first_line_header

@let model = rc

model -ind "${model}" -column_type "0#real:format=%gM"

plot -type bar -columns "category=1,value=0,color=2,label=3" -ymax 8000

@let plot1 = rc

set -view view1 -plot "${plot1}" -name dataLabel.visible -value 1
set -view view1 -plot "${plot1}" -name dataLabel.position -value TOP_OUTSIDE
set -view view1 -plot "${plot1}" -name invertY -value 1
set -view view1 -plot "${plot1}" -name "Y Axis.grid.line.visible" -value 1
