CDEBUG = -g

PROG = charts_test_module

CPP_SRC = \
test.cpp \

EXTRA_CFLAGS = \
-I$(INC_DIR)/CQCharts \
-I$(INC_DIR)/CMandelbrot \
-I$(INC_DIR)/CPointFractal \
-I$(INC_DIR)/CQUtil \
-I$(INC_DIR)/CQFillTexture \
-I$(INC_DIR)/CColorRange \
-I$(INC_DIR)/CMath \
-I$(INC_DIR)/CRGBA \
-I$(INC_DIR)/COS \
\
-I/usr/include/x86_64-linux-gnu/qt5/QtWidgets \
-I/usr/include/x86_64-linux-gnu/qt5/QtGui \
-I/usr/include/x86_64-linux-gnu/qt5/QtCore \
-I/usr/include/x86_64-linux-gnu/qt5 \

include $(MAKE_DIR)/shlib.mk
